// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPay.Web.Data;

#nullable disable

namespace PersonalPay.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PersonalPay.Web.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PersonalPay.Web.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LembreteEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixCopiaECola")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixQrCodeBase64")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("PersonalPay.Web.Models.WebhookEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificacaoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotificacaoId")
                        .IsUnique();

                    b.ToTable("WebhookEventos");
                });

            modelBuilder.Entity("PersonalPay.Web.Models.Cobranca", b =>
                {
                    b.HasOne("PersonalPay.Web.Models.Cliente", "Cliente")
                        .WithMany("Cobrancas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PersonalPay.Web.Models.Cliente", b =>
                {
                    b.Navigation("Cobrancas");
                });
#pragma warning restore 612, 618
        }
    }
}
